version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    networks:
      - laravelnet
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:15
    container_name: postgres_laravel
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravelnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_laravel
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - laravelnet

volumes:
  pgdata:

networks:
  laravelnet:
    driver: bridge